### ISSUE TITLE
Add support to read and parse encrypted metadata

### ISSUE THREAD

**Issue by bathienle** [Cytomine-ULiege/pims-plugin-format-dicom#11]
# Description

Add support to read and parse the encrypted metadata associated to a dataset.

# Task

- [ ] Decrypt the xml metadata files
- [ ] Parse the xml files
- [ ] Create associated Cytomine property to these metadata

**Comment by bathienle** [comment]
Done in Cytomine-ULiege/bigpicture-pims#5
